development: &DEVELOPMENT
  adapter: sqlite3
  timeout: 5000
  database: db/development.sqlite3

test: &TEST
  adapter: sqlite3
  timeout: 5000
  database: db/test.sqlite3

production: &PRODUCTION
  adapter: mysql
  database: pelorus_production
  username: pelorus
  encoding: utf8

cucumber:
  <<: *TEST