development:
  users:
    admin:
      password: pelorus
      write_permission: true
    collaborator:
      password: pelorus
      write_permission: false
    stenning:
      password: pelorus
      write_permission: true
